name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        name: Setup Rust
        with:
          targets: wasm32-unknown-unknown
          components: trunk
      - run: trunk build --config Trunk-Release.toml
        name: Build
      - uses: JamesIves/github-pages-deploy-action@v4
        name: Deploy
        with:
          folder: dist
