name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions-rs/toolchain@v1
        name: Setup Rust
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - name: Setup Trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.17.5/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - uses: actions/cache@v3
        name: Cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: ./trunk build --config Trunk-Release.toml
        name: Build
      - uses: JamesIves/github-pages-deploy-action@v4
        name: Deploy
        with:
          folder: dist
