on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: actions/github-script@v5
        id: build-info
        with:
          script: |
            const search = await github.request('GET /repos/{owner}/{repo}/git/commits/{commit_sha}', {
              owner: 'PyrrhaDevs',
              repo: 'pyrrha.dev',
              commit_sha: context.sha
            });
            
            let commit = {};
            if(search.status == 200) {
              commit = search.data
            };
            core.warn(JSON.stringify(search.data));
            let output = {
              sha: context.sha
            };
            
            if(commit != {} && commit != undefined) {
               output.username = commit.author.login;
               output.date     = commit.commit.author.date;
               output.message  = commit.commit.message;
            } else {
              output.username  = "octocat";
              output.date      = new Date().toISOString();
              output.message   = "unknown: could not retrive commit at build time.";
              core.warning(`Using default output data since seach has no items. Search response: ${JSON.stringify(commit)}`);
            }
            
            core.setOutput('buildInfo', JSON.stringify(output));
            core.info(`Build Info: ${JSON.stringify(output)}`);
      - run: yarn install
      - run: yarn build
        env:
          REACT_APP_BUILD_INFO: ${{ steps.build-info.outputs.buildInfo }}
      - id: get-sha
        shell: bash
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          full_commit_message: 'ci: publish ${{ steps.get-sha.outputs.sha }}'
