on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: actions/github-script@v5
        id: build-info
        with:
          script: |
            core.info(`Getting commit info for ${context.sha}`);
            const commit = await github.rest.search.commits({
              q: `hash:${context.sha}`,
              per_page: 1
            });
            
            let output = {
              sha: context.sha
            };
            
            if(commit.items != null && commit.items.length > 0) {
               output.username = commit.items[0].author.login;
               output.date     = commit.items[0].commit.author.date;
               output.message  = commit.items[0].commit.message;
            } else {
              output.username  = "octocat"
              output.date      = new Date().toISOString();
              output.message   = "unknown: could not retrive commit at build time."
            }
            
            core.setOutput('buildInfo', JSON.stringify(output));
            core.info(`Build Info: ${JSON.stringify(output)}`);
      - run: yarn install
      - run: yarn build
        env:
          REACT_APP_BUILD_INFO: ${{ steps.build-info.outputs.buildInfo }}
      - id: get-sha
        shell: bash
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          full_commit_message: 'ci: publish ${{ steps.get-sha.outputs.sha }}'
